# Task 1: Regression Analysis
 Description: Perform a simple linear regression analysis to predict one variable based on another.

In [25]:
import pandas as pd 
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

Load Data Using Pandas

In [5]:
data = pd.read_csv("../../Data Set For Task/2) Stock Prices Data Set.csv")
data

       symbol        date      open      high       low     close    volume
0         AAL  2014-01-02   25.0700   25.8200   25.0600   25.3600   8998943
1        AAPL  2014-01-02   79.3828   79.5756   78.8601   79.0185  58791957
2         AAP  2014-01-02  110.3600  111.8800  109.2900  109.7400    542711
3        ABBV  2014-01-02   52.1200   52.3300   51.5200   51.9800   4569061
4         ABC  2014-01-02   70.1100   70.2300   69.4800   69.8900   1148391
...       ...         ...       ...       ...       ...       ...       ...
497467    XYL  2017-12-29   68.5300   68.8000   67.9200   68.2000   1046677
497468    YUM  2017-12-29   82.6400   82.7100   81.5900   81.6100   1347613
497469    ZBH  2017-12-29  121.7500  121.9500  120.6200  120.6700   1023624
497470   ZION  2017-12-29   51.2800   51.5500   50.8100   50.8300   1261916
497471    ZTS  2017-12-29   72.5500   72.7600   72.0400   72.0400   1704122

[497472 rows x 7 columns]

Data Cleaning

In [6]:
data.isna().sum()

symbol     0
date       0
open      11
high       8
low        8
close      0
volume     0
dtype: int64

In [8]:
imputer = SimpleImputer(strategy="median")
numericData = data.drop(["symbol", "date"],axis=1)
imputedArray = imputer.fit_transform(numericData)
imputedDF = pd.DataFrame(imputedArray, columns=numericData.columns)
finalData = pd.concat([data[["symbol", "date"]].reset_index(drop=True), imputedDF], axis=1)
finalData

       symbol        date      open      high       low     close      volume
0         AAL  2014-01-02   25.0700   25.8200   25.0600   25.3600   8998943.0
1        AAPL  2014-01-02   79.3828   79.5756   78.8601   79.0185  58791957.0
2         AAP  2014-01-02  110.3600  111.8800  109.2900  109.7400    542711.0
3        ABBV  2014-01-02   52.1200   52.3300   51.5200   51.9800   4569061.0
4         ABC  2014-01-02   70.1100   70.2300   69.4800   69.8900   1148391.0
...       ...         ...       ...       ...       ...       ...         ...
497467    XYL  2017-12-29   68.5300   68.8000   67.9200   68.2000   1046677.0
497468    YUM  2017-12-29   82.6400   82.7100   81.5900   81.6100   1347613.0
497469    ZBH  2017-12-29  121.7500  121.9500  120.6200  120.6700   1023624.0
497470   ZION  2017-12-29   51.2800   51.5500   50.8100   50.8300   1261916.0
497471    ZTS  2017-12-29   72.5500   72.7600   72.0400   72.0400   1704122.0

[497472 rows x 7 columns]

In [9]:
finalData.drop_duplicates(inplace=True)

In [10]:
finalData

       symbol        date      open      high       low     close      volume
0         AAL  2014-01-02   25.0700   25.8200   25.0600   25.3600   8998943.0
1        AAPL  2014-01-02   79.3828   79.5756   78.8601   79.0185  58791957.0
2         AAP  2014-01-02  110.3600  111.8800  109.2900  109.7400    542711.0
3        ABBV  2014-01-02   52.1200   52.3300   51.5200   51.9800   4569061.0
4         ABC  2014-01-02   70.1100   70.2300   69.4800   69.8900   1148391.0
...       ...         ...       ...       ...       ...       ...         ...
497467    XYL  2017-12-29   68.5300   68.8000   67.9200   68.2000   1046677.0
497468    YUM  2017-12-29   82.6400   82.7100   81.5900   81.6100   1347613.0
497469    ZBH  2017-12-29  121.7500  121.9500  120.6200  120.6700   1023624.0
497470   ZION  2017-12-29   51.2800   51.5500   50.8100   50.8300   1261916.0
497471    ZTS  2017-12-29   72.5500   72.7600   72.0400   72.0400   1704122.0

[497472 rows x 7 columns]

Data Preparation (Normalization)

In [12]:
finalData.drop(['symbol','date'], axis=1, inplace=True)
finalData

            open      high       low     close      volume
0        25.0700   25.8200   25.0600   25.3600   8998943.0
1        79.3828   79.5756   78.8601   79.0185  58791957.0
2       110.3600  111.8800  109.2900  109.7400    542711.0
3        52.1200   52.3300   51.5200   51.9800   4569061.0
4        70.1100   70.2300   69.4800   69.8900   1148391.0
...          ...       ...       ...       ...         ...
497467   68.5300   68.8000   67.9200   68.2000   1046677.0
497468   82.6400   82.7100   81.5900   81.6100   1347613.0
497469  121.7500  121.9500  120.6200  120.6700   1023624.0
497470   51.2800   51.5500   50.8100   50.8300   1261916.0
497471   72.5500   72.7600   72.0400   72.0400   1704122.0

[497472 rows x 5 columns]

In [14]:
scaler = MinMaxScaler()

In [17]:
finalData[['norm_open', 'norm_high', 'norm_low', 'norm_close']] = scaler.fit_transform(
    finalData[['open', 'high', 'low', 'close']]
)
finalData.head()

,open,high,low,close,volume,norm_open,norm_high,norm_low,norm_close
0,25.0700,25.8200,25.0600,25.3600,8998943.0,0.011482,0.011678,0.011585,0.011610
1,79.3828,79.5756,78.8601,79.0185,58791957.0,0.038075,0.037693,0.038041,0.037818
2,110.3600,111.8800,109.2900,109.7400,542711.0,0.053242,0.053327,0.053004,0.052823
3,52.1200,52.3300,51.5200,51.9800,4569061.0,0.024726,0.024508,0.024597,0.024612
4,70.1100,70.2300,69.4800,69.8900,1148391.0,0.033534,0.033170,0.033428,0.033359

In [18]:
finalData.drop(['open','high','low','close'], axis=1, inplace=True)
finalData

            volume  norm_open  norm_high  norm_low  norm_close
0        8998943.0   0.011482   0.011678  0.011585    0.011610
1       58791957.0   0.038075   0.037693  0.038041    0.037818
2         542711.0   0.053242   0.053327  0.053004    0.052823
3        4569061.0   0.024726   0.024508  0.024597    0.024612
4        1148391.0   0.033534   0.033170  0.033428    0.033359
...            ...        ...        ...       ...         ...
497467   1046677.0   0.032761   0.032478  0.032661    0.032534
497468   1347613.0   0.039669   0.039210  0.039383    0.039084
497469   1023624.0   0.058819   0.058201  0.058576    0.058161
497470   1261916.0   0.024315   0.024130  0.024248    0.024050
497471   1704122.0   0.034729   0.034395  0.034687    0.034409

[497472 rows x 5 columns]

Split the dataset into training and testing sets

In [21]:
X = finalData.drop('volume', axis=1)
y = finalData['volume']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

Shape of X_train: (397977, 4)
Shape of X_test: (99495, 4)
Shape of y_train: (397977,)
Shape of y_test: (99495,)

 Fit a linear regression model using scikit-learn.

In [23]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

Interpret the coefficients and evaluate the model using metrics such as R-squared and mean squared error.

In [24]:
y_pred = model.predict(X_test)

In [26]:
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
r2 = r2_score(y_test, y_pred)
print(f"R2 Score: {r2}")

Mean Squared Error: 68727161420843.43
R2 Score: 0.0270199324790813